version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')\" | python manage.py shell && gunicorn --bind 0.0.0.0:8000 credit_card_api.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
